spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework.web: DEBUG
    com.board: DEBUG

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity-time: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity-time: ${JWT_REFRESH_TOKEN_VALIDITY}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}


